language: java
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - llvm-3.8
      - clang-3.8

script:
  - ./gradlew check --stacktrace --info
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
